##############################
#    Medusa Configuration    #
##############################
# This is the configuration file for Medusa Anticheat.

# Anticheat testing mode.
# If enabled, no punishments will occur and alerts will enable automatically on join.
#
testmode: false

# Anticheat response configuration.
# If you want to change how the anticheat looks/responds, you can do it here.
#
response:
  general:
    prefix: '&8[&2Medusa&8]'
    no-permission: '&cNo permission.'
  command:
    prefix: '&8[&2Medusa&8]&c'
    name: 'medusa' # Broken for now, this does not affect anything


violations:
  # minimum-vl: How much VL the check has to get in order to alert.
  # alert-format: Alert format for flagging.
  # clear-violations-delay: Clears violations for all checks every specified time (in minutes)
  minimum-vl: 5
  alert-format: '%prefix% &a%player% &2- &a%check% (Type %type%) %dev% &8[&cVL: %vl%&8]'
  clear-violations-delay: 10

# Check configuration
#
#
# enabled: Turns the check on/off.
# max-violations: Amount of times a player can flag before running the specified punish-command.
# punish-command: Command ran by the server when a player exceeds the specified max-violations.
#
#
#
checks:
  combat:
    aim:
      a:
        enabled: true
        max-violations: 100
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        max-violations: 100
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      c:
        enabled: true
        max-violations: 100
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      d:
        enabled: true
        max-violations: 100
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      e:
        enabled: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    autoclicker:
      a:
        enabled: true
        max-violations: 10
        punish-command: 'ban %player% %prefix% Unfair Advantage'
        # max-cps: How fast one can click before getting flagged.
        max-cps: 25
      b:
        enabled: true
        max-violations: 100
        punish-command: ''
    killaura:
      a:
        enabled: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        max-violations: 200
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      c:
        enabled: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      d:
        enabled: true
        max-violations: 25
        punish-command: 'ban %player% %prefix% Unfair Advantage'
        # sample-size: How much data for this check. Going higher means higher stability, but slower detection, vice versa for smaller sample size.
        # max-accuracy: How accurate the player can be. Set to as high as your sample-size. Higher limit means more stablility.
        sample-size: 100
        max-accuracy: 85
      e:
        enabled: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    reach:
      a:
        enabled: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
        # max-reach: Maximum hit-reach. If you have false flags increase this number to 3.0-6.0.
        # reach-sensitivity: (Scale of 1-5) 1-3 makes the check less prone to false flags. 4-5 increases detection rate.
        # reach-maxlatency: In milliseconds, the maximum ping a player can have before the reach check is disabled.
        # If you are having false positives with lag increase this.
        max-reach: 3.25
        reach-sensitivity: 4
        reach-maxlatency: 200
    velocity:
      # Would recommend leaving this disabled, some falses occur.
      a:
        enabled: false
        max-violations: 100
        punish-command: 'ban %player% %prefix% Unfair Advantage'
  movement:
    fastclimb:
      a:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    flight:
      a:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    jesus:
      a:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      c:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    motion:
      a:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      c:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      d:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      e:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      f:
        enabled: true
        setback: false
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    nofall:
      a:
        enabled: true
        setback: false
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    speed:
      a:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      c:
        enabled: true
        setback: true
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
  player:
    badpackets:
      a:
        enabled: true
        max-violations: 1
        punish-command: 'kick %player% %prefix% Invalid rotation detected!'
      b:
        enabled: true
        max-violations: 20
        punish-command: 'kick %player% %prefix% Invalid packets detected! Hacking?'
      c:
        enabled: true
        max-violations: 25
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      d:
        enabled: true
        max-violations: 50
        punish-command: 'kick %player% %prefix% Invalid packets detected! Hacking?'
    inventory:
      # Highly experimental, would recommend leaving this disabled.
      a:
        enabled: false
        max-violations: 50
        punish-command: 'ba %player% %prefix% Unfair Advantage'
      b:
        enabled: false
        max-violations: 50
        punish-command: 'ba %player% %prefix% Unfair Advantage'
    pingspoof:
      a:
        enabled: true
        max-violations: 100
        punish-command: 'kick %player% %prefix% Unfair Advantage'
        # max-ping-difference: The maximum ping difference. Usually legit players hover between 50-100ms, PingSpoof users will be higher. Adjust at your risk.
        # max-buffer: Making this higher reduces detection, but makes the check less prone to false positives. Lowering this value will do the opposite.
        max-ping-difference: 500
        max-buffer: 200
    scaffold:
      a:
        enabled: true
        max-violations: 25
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        max-violations: 75
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      c:
        enabled: false
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    timer:
      a:
        enabled: true
        max-violations: 10
        punish-command: 'kick %player% %prefix% Invalid packet rate.'
        # max-timer-speed: Maximum timer speed, make this higher if you have false positives.
        # min-timer-speed: Minimum timer speed, make this lower if you have false positives.
        # max-buffer: Make this higher to reduce falses, lower to increase detection.
        max-timer-speed: 1.1
        min-timer-speed: 0.9
        max-buffer: 2
      b:
        enabled: true
        max-violations: 10
        punish-command: 'kick %player% %prefix% Invalid packet rate.'
        # max-packet-discrepancy: The leniency of the check, recommended to stay in the range of 2-7.
        # max-buffer: Make this higher to reduce falses, lower to increase detection.
        max-packet-discrepancy: 2
        max-buffer: 2