name: Medusa
version: 1.4.2-HOTFIX-1
main: com.gladurbad.medusa.Medusa
load: STARTUP
authors: [ GladUrBad ]
softdepend: [PlaceholderAPI]

commands:
  medusa:
    description: Medusa Anticheat commands.
    usage: /<command>
