name: Medusa
version: 1.5
main: com.gladurbad.medusa.MedusaPlugin
authors: [GladUrBad]
description: Medusa Anticheat

commands:
  medusa:
    description: Commands for Medusa Anticheat.
    usage: /medusa
    aliases: [anticheat, ac]
    permission: medusa.commands
  alerts:
    description: Toggles alerts for Medusa Anticheat.
    usage: /alerts
    permission: medusa.alerts


