##############################
#    Medusa Configuration    #
##############################
# This is the configuration file for Medusa Anticheat.

# Anticheat testing mode.
# If enabled, no punishments will occur and alerts will enable automatically on join.
testmode: false

# Anticheat response configuration.
# If you want to change how the anticheat looks/responds, you can do it here.
response:
  general:
    prefix: '&8[&2Medusa&8]'
    no-permission: '&cNo permission.'
  violations:
    minimum-vl: 3
    alert-format: '%prefix% &a%player% &2- &a%check% (Type %type%) %dev% &8[&cVL: %vl%&8]'
  command:
    prefix: '&8[&2Medusa&8]&c'
    name: 'medusa' # Broken for now, this does not affect anything


# Check configuration
checks:
  combat:
    autoclicker:
      a:
        enabled: true
        # max-cps: Maximum clicks per seconds the player can click.
        max-cps: 20
        max-violations: 30
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    killaura:
      a:
        enabled: true
        max-violations: 30
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        max-violations: 30
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      c:
        enabled: true
        max-violations: 30
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      d:
        enabled: true
        max-violations: 30
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      e:
        enabled: true
        # swings: Minimum amount of swings to check the detection.
        swings: 100
        # min-flag: Minimum amount of hits to flag.
        min-flag: 75
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      f: #VERY INACCURATE - Make the RayCasting more accurate for it to be usable.
        enabled: false
        # swings: Minimum amount of swings to check the detection.
        swings: 100
        # min-flag: Minimum amount of potential hits that haven't been landed to flag.
        min-flag: 45
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    reach:
      a:
        enabled: true
        # max-reach: Maximum hit-reach. If you have false flags increase this number to 3.0-6.0.
        # 4-5 may produce false positives, but increase the effectiveness of the check.
        max-reach: 3.5
        # reach-sensitivity: (Scale of 1-5) 1-3 makes the check less prone to false flags.
        reach-sensitivity: 3
        # reach-maxlatency: In milliseconds, the maximum ping a player can have before the reach check is disabled.
        # If you are having false positives with lag increase this.
        reach-maxlatency: 200
        max-violations: 50
        punish-command: 'ban %player% %prefix% Unfair Advantage'
  movement:
    fastclimb:
      a:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    flight:
      a:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    jesus:
      a:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      c:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    motion:
      a:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      c:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      d:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      e:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    nofall:
      a:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    speed:
      a:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
  player:
    badpackets:
      a:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      b:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
      c:
        enabled: true
        setback: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'
    timer:
      a:
        enabled: true
        max-violations: 20
        punish-command: 'ban %player% %prefix% Unfair Advantage'