##############################
#    Medusa Configuration    #
##############################
# This is the configuration file for Medusa Anticheat.

# Anticheat testing mode.
# If enabled, no punishments will occur and alerts will enable automatically on join.
testmode: false

# Anticheat response configuration.
# If you want to change how the anticheat looks/responds, you can do it here.
response:
  general:
    prefix: '&8[&2Medusa&8]'
    no-permission: '&cNo permission.'
  violations:
    minimum-vl: 3
    alert-format: '%prefix% &a%player% &2- &a%check% (Type %type%) %dev% &8[&cVL: %vl%&8]'
  command:
    prefix: '&8[&2Medusa&8]&c'
    name: 'medusa' # Broken for now, this does not affect anything


# Check configuration
#
# enabled: Whether or not this check is being used.
# max-vl: The maximum amount of vl the check can have.
# vl-add: Amount of vl to add to the checks overall vl.
# vl-decay: Amount of time between each vl decrement (in ticks).
# vl-delay: Amount of time between last fail to start decrementing vl (in ticks).
#
# Violation works by each check having their own VL (Violation Level) which is
# incremented by one every time the player fails the check. Its VL adds to the
# "global" VL (for example KillAuraA's VL will add to the total of KillAura's VL)
# which will determin what commands will be taken (if any).
#
# Example:
#
# KillAuraA has a total of 5 VL and its vl-add is set to 2.0. This means that
# KillAura's VL is 10 because 5*2.0=10.
# KillAuraB has a total of 10 VL and its vl-add is set to 0.5. This means that
# KillAura's VL is now 15 because 10+10*0.5=5. (10 from KillAuraA's VL)
#
checks:
  combat:
    autoclicker:
      a:
        enabled: true
        # max-cps: Maximum clicks per seconds the player can click.
        max-cps: 20
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']
    killaura:
      a:
        enabled: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      b:
        enabled: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      c:
        enabled: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      d:
        enabled: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      e:
        enabled: true
        # swings: Minimum amount of swings to check the detection.
        swings: 100
        # min-flag: Minimum amount of hits to flag.
        min-flag: 75
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      f: #VERY INACCURATE - Make the RayCasting more accurate for it to be usable.
        enabled: false
        # swings: Minimum amount of swings to check the detection.
        swings: 100
        # min-flag: Minimum amount of potential hits that haven't been landed to flag.
        min-flag: 45
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']
    reach:
      a:
        enabled: true
        # max-reach: Maximum hit-reach. If you have false flags increase this number to 3.0-6.0.
        # 4-5 may produce false positives, but increase the effectiveness of the check.
        max-reach: 3.5
        # reach-sensitivity: (Scale of 1-5) 1-3 makes the check less prone to false flags.
        reach-sensitivity: 3
        # reach-maxlatency: In milliseconds, the maximum ping a player can have before the reach check is disabled.
        # If you are having false positives with lag increase this.
        reach-maxlatency: 200
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']
  movement:
    fastclimb:
      a:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']
    flight:
      a:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      b:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']
    jesus:
      a:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      b:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      c:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']
    motion:
      a:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      b:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      c:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      d:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      e:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']
    nofall:
      a:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']
    speed:
      a:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      b:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']
  player:
    badpackets:
      a:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      b:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      c:
        enabled: true
        setback: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']
    timer:
      a:
        enabled: true
        max-vl: 30
        vl-add: 1.0
        vl-decay: 20
        vl-delay: 1000
      commands:
        '50': ['ban %player% %prefix% Unfair Advantage']