################################
#     AntiMoveHack Config      #
################################
#
# Meme developed by GladUrBad#8395
#
# Checks
#
# How to configure check:
#
#
# sensitivity: This number (1-5) determines how sensitive the check is, a high sens may help detection but increase false positives, a low sens will do the opposite. 0 will disable the check.
# punishvl: This number determines at what VL the check will punish for, put 0 if you do not want to punish.
# punishcommand: This is the command that will be run when the VL is exceeded. Leave blank to do nothing.
#
#
fastclimb:
  a:
    sensitivity: 3
    punishvl: 20
    punishcommand: ''
flight:
  a:
    sensitivity: 3
    punishvl: 20
    punishcommand: ''
jesus:
  a:
    sensitivity: 3
    punishvl: 20
    punishcommand: ''
  b:
    sensitivity: 3
    punishvl: 20
    punishcommand: ''
motion:
  a:
    sensitivity: 3
    punishvl: 20
    punishcommand: ''
  b:
    sensitivity: 3
    punishvl: 20
    punishcommand: ''
  c:
    sensitivity: 3
    punishvl: 20
    punishcommand: ''
speed:
  a:
    sensitivity: 3
    punishvl: 20
    punishcommand: ''
timer:
  a:
    sensitivity: 3
    punishvl: 20
    punishcommand: ''